//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mzinga.Viewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mzinga.Viewer.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}.
        /// </summary>
        internal static string BoardHistoryItemFormat {
            get {
                return ResourceManager.GetString("BoardHistoryItemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Console.
        /// </summary>
        internal static string EngineConsoleTitle {
            get {
                return ResourceManager.GetString("EngineConsoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception details: {0}.
        /// </summary>
        internal static string ExceptionViewModelDetailsFormat {
            get {
                return ResourceManager.GetString("ExceptionViewModelDetailsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string GameOverTitle {
            get {
                return ResourceManager.GetString("GameOverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s black&apos;s turn..
        /// </summary>
        internal static string GameStateBlacksTurn {
            get {
                return ResourceManager.GetString("GameStateBlacksTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black has won the game..
        /// </summary>
        internal static string GameStateBlackWon {
            get {
                return ResourceManager.GetString("GameStateBlackWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is a draw..
        /// </summary>
        internal static string GameStateDraw {
            get {
                return ResourceManager.GetString("GameStateDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game has not been started..
        /// </summary>
        internal static string GameStateNoGame {
            get {
                return ResourceManager.GetString("GameStateNoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s white&apos;s turn..
        /// </summary>
        internal static string GameStateWhitesTurn {
            get {
                return ResourceManager.GetString("GameStateWhitesTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White has won the game..
        /// </summary>
        internal static string GameStateWhiteWon {
            get {
                return ResourceManager.GetString("GameStateWhiteWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string NewGameTitle {
            get {
                return ResourceManager.GetString("NewGameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer Settings.
        /// </summary>
        internal static string ViewerConfigTitle {
            get {
                return ResourceManager.GetString("ViewerConfigTitle", resourceCulture);
            }
        }
    }
}
